framework: jest
tier: xsmall
postMerge: 
  pattern: 
    - "./packages/xstate-test/test/*.test.ts"
preMerge:
  pattern: 
    - "./packages/xstate-test/test/*.test.ts"
preRun:
     command:
        - yarn install
postRun:
     command:
        - yarn --version
version: 1.0
