framework: jest
tier: xsmall
postMerge: 
  pattern: 
    - "./packages/xstate-test/test/*.test.ts"
    - "./packages/xstate-vue/test/*.test.ts"
    - "./packages/xstate-react/test/*.test.tsx"
preMerge:
  pattern: 
    - "./packages/xstate-test/test/*.test.ts"
    - "./packages/xstate-vue/test/*.test.ts"
    - "./packages/xstate-react/test/*.test.tsx"
preRun:
     command:
        - yarn install
postRun:
     command:
        - yarn --version
version: 1.0
