framework: jest
tier: xsmall
postMerge: 
  pattern: 
    - "./packages/**/*.test.ts"
    - "./packages/**/*.test.tsx"
preMerge:
  pattern: 
    - "./packages/**/*.test.ts"
    - "./packages/**/*.test.tsx"
preRun:
     command:
        - yarn install
postRun:
     command:
        - yarn --version
version: 1.0
